version: '3.4'
services:
  board.api:
    image: ${DOCKER_REGISTRY-}boardapi
    container_name: board.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
      - "8081:5001"
    
  board.database:
    image: postgres:latest
    container_name: board.database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: TaskBoardDb
    volumes:
      - ./.containers/board-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"