version: '3.4'

networks:
  dev:
    driver: bridge

services:
  board_api:
    image: ${DOCKER_REGISTRY-}board_api
    depends_on:
      - board_db
    container_name: board_api
    ports:  
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=board_db;UserId=postgres;Password=postgres;Database=TaskBoardDb;Pooling=true;"
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - dev
    
  board_db:
    image: postgres:latest
    container_name: board_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TaskBoardDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:    
